name: Sunday Reminder Bot

on:
  schedule:
    # Run every Saturday at 22:00 Moscow time (UTC+3)
    # Cron format: minute hour day month day-of-week
    # Moscow time is UTC+3, so 22:00 Moscow = 19:00 UTC
    - cron: '0 19 * * 6'
  workflow_dispatch: # Allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Build and run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
      run: |
        go mod download
        make build
        make run
        
    - name: Bot execution status
      run: |
        echo "Bot execution completed at $(date)"
        echo "If you see 'reminder sent; exiting' above, the bot ran successfully"
